# Try / Except

Quando rodamos nosso código e ele apresenta um erro, podemos tratar esse erro para o usuário corrigi-lo e continuar com a execução do programa, ou seja, o comando **try** (como o nome diz) vai tentar executar a ação, e caso de erro, o comando **except** vai trazer uma mensagem "tratada".

Veja o exemplo, enquanto o input não for um número, ele mostra o erro, porém não quebra o laço de repetição.

~~~python
#Calculo de temperatura celsius para Kelvin
while True:
    try:
        celsius = float(input('Digite a temperatura em graus Celsius: '))


        kelvin = (celsius + 273)

        print(f'{celsius}° Celsius equivale a {kelvin} Kelvin')
        break
        
    except:
        print('Erro - Por favor insira um número válido! \n')
~~~

## Fixando a ideia
Vamos rodar um programa onde tratamos erros específicos

~~~python
nome= ['Ana', 'Julio', 'Maria', 'Rodolfo']

for tentativa in range(3):
    
    try:
        num= int(input('Digite o indice para imprimir o nome: '))
        print(nome[num])
        
    except ValueError:
        print('Erro :( - Digite um número \n') 
        
    except IndexError:
        print('Valor inválido :( - digite entre 4 e -4 \n')
~~~

Note os erros específicos: 
ValueError-> erro causado quando tentamos converter um caractere em número
IndexError-> quando tentamos acessar um índice inválido numa lista (ou estrutura similar)

Veja mais em:
https://docs.python.org/pt-br/3/library/exceptions.html#bltin-exceptions
